name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  pages: write # to deploy to Pages
  id-token: write

jobs:
  # create-or-update-pr:
  #   name: Create or update PR
  #   uses: ./.github/workflows/create-pr.yaml

  build-and-deploy-to-pages:
    name: Build website and deploy to GitHub Pages
    uses: ./.github/workflows/deploy.yaml
